export type ProductCategory =
  | 'AI Tools'
  | 'Design'
  | 'Streaming'
  | 'Music'
  | 'Learning'
  | 'Cloud'
  | 'VPN & Security'
  | 'Developer'
  | 'Communication'
  | 'Gaming'
  | 'Business'

export type Badge = 'best_seller' | 'new' | 'instant'

export interface Plan {
  name: string
  duration: string
  price: number
  originalPrice: number
  popular?: boolean
}

export interface ProductReview {
  name: string
  role: string
  initial: string
  rating: number
  comment: string
}

export interface ProductFaq {
  q: string
  a: string
}

export interface CatalogProduct {
  slug: string
  name: string
  tier: string
  category: ProductCategory
  logo?: string
  logoText?: string
  whiteLogo?: boolean
  tile: string
  description: string
  features: string[]
  plans: Plan[]
  warranty: string
  deliveryTime: string
  status: 'available' | 'out_of_stock'
  badges: Badge[]
  activationGuide: string
  termsConditions: string[]
  faq: ProductFaq[]
  reviews: ProductReview[]
  relatedSlugs: string[]
}

// ─── helpers ────────────────────────────────────────────────────────────────

function plans(m1: number, m3: number, m6: number, yr: number, pop: 0 | 1 | 2 | 3 = 0): Plan[] {
  const mult = [1.8, 1.7, 1.6, 1.5]
  return [
    { name: '1 Bulan',  duration: '30 Hari',  price: m1,  originalPrice: Math.round(m1 * mult[0] / 500) * 500, popular: pop === 0 },
    { name: '3 Bulan',  duration: '90 Hari',  price: m3,  originalPrice: Math.round(m3 * mult[1] / 500) * 500, popular: pop === 1 },
    { name: '6 Bulan',  duration: '180 Hari', price: m6,  originalPrice: Math.round(m6 * mult[2] / 500) * 500, popular: pop === 2 },
    { name: '1 Tahun',  duration: '365 Hari', price: yr,  originalPrice: Math.round(yr  * mult[3] / 500) * 500, popular: pop === 3 },
  ]
}

const commonReviews: ProductReview[] = [
  { name: 'Andi Pratama', role: 'Content Creator', initial: 'A', rating: 5, comment: 'Akun langsung aktif kurang dari satu menit. Sangat memuaskan!' },
  { name: 'Dewi Lestari', role: 'Mahasiswa', initial: 'D', rating: 5, comment: 'Harga paling murah, proses instan, dan support responsif.' },
  { name: 'Rizky Maulana', role: 'Freelancer', initial: 'R', rating: 4, comment: 'Sudah beli berkali-kali, selalu memuaskan dan garansinya beneran dipakai.' },
]

const commonTerms = [
  'Akun bersifat shared — tidak boleh mengganti password atau email utama.',
  'Garansi penggantian akun selama periode berlangganan jika terjadi kendala.',
  'Dilarang keras menggunakan akun untuk aktivitas ilegal.',
  'Tidak dapat digunakan bersamaan di lebih dari perangkat yang ditentukan.',
  'Hubungi support maksimal 1×24 jam setelah akun bermasalah.',
]

const commonFaq: ProductFaq[] = [
  { q: 'Berapa lama proses aktivasi?', a: 'Rata-rata kurang dari 1 menit setelah pembayaran terkonfirmasi.' },
  { q: 'Bagaimana cara menggunakan akun?', a: 'Detail login akan tampil di dashboard. Ikuti panduan aktivasi yang disertakan.' },
  { q: 'Apakah ada garansi?', a: 'Ya, semua produk bergaransi 30 hari. Akun bermasalah akan kami ganti tanpa biaya.' },
  { q: 'Bisakah diakses di beberapa perangkat?', a: 'Tergantung kebijakan layanan. Detail tercantum di deskripsi produk.' },
]

// ─── catalog ────────────────────────────────────────────────────────────────

export const catalog: CatalogProduct[] = [
  // ── AI Tools ────────────────────────────────────────────────────────────
  {
    slug: 'chatgpt-plus',
    name: 'ChatGPT', tier: 'Plus',
    category: 'AI Tools',
    logo: '/logos/chatgpt.svg', whiteLogo: true,
    tile: 'linear-gradient(150deg,#0f9d7a,#0a6b56)',
    description: 'Akses GPT-4o, DALL·E 3, browsing web, dan plugin eksklusif. Tingkatkan produktivitas dengan AI paling canggih dari OpenAI.',
    features: ['GPT-4o & GPT-4 Turbo', 'Browsing Web Real-time', 'DALL·E 3 Image Gen', 'Plugin & GPTs Store', 'File Upload & Analysis', 'Priority Access'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Login ke chat.openai.com\n2. Masukkan email & password\n3. Klik "Try Plus" lalu aktif otomatis\n4. Nikmati semua fitur premium',
    termsConditions: commonTerms,
    faq: commonFaq,
    reviews: commonReviews,
    relatedSlugs: ['claude-pro', 'gemini-advanced', 'perplexity-pro'],
  },
  {
    slug: 'claude-pro',
    name: 'Claude', tier: 'Pro',
    category: 'AI Tools', logoText: 'Claude',
    tile: 'linear-gradient(150deg,#d97706,#92400e)',
    description: 'AI dari Anthropic dengan kemampuan analisis teks panjang, coding canggih, dan keamanan tinggi. Ideal untuk profesional dan developer.',
    features: ['Claude 3.5 Sonnet & Opus', '200K Context Window', 'File & Document Analysis', 'Advanced Coding', 'Priority Access', 'Early Feature Access'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka claude.ai\n2. Login dengan akun yang diberikan\n3. Pilih model Claude Pro\n4. Mulai chat',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['chatgpt-plus', 'gemini-advanced'],
  },
  {
    slug: 'gemini-advanced',
    name: 'Gemini', tier: 'Advanced',
    category: 'AI Tools', logoText: 'Gemini',
    tile: 'linear-gradient(150deg,#1a73e8,#0052cc)',
    description: 'Google Gemini Ultra 1.5 — AI multimodal terdepan Google. Analisis gambar, video, kode, dan teks panjang dalam satu platform.',
    features: ['Gemini Ultra 1.5', 'Multimodal (Teks, Gambar, Video)', '1M Token Context', 'Google Workspace Integration', 'Advanced Reasoning', '2TB Google One Storage'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka gemini.google.com\n2. Login dengan akun Google yang diberikan\n3. Aktifkan Gemini Advanced\n4. Mulai gunakan',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['chatgpt-plus', 'microsoft-copilot-pro'],
  },
  {
    slug: 'perplexity-pro',
    name: 'Perplexity', tier: 'Pro',
    category: 'AI Tools', logoText: 'Perplexity',
    tile: 'linear-gradient(150deg,#1c1c2e,#0a0a1a)',
    description: 'Mesin pencari bertenaga AI. Dapatkan jawaban akurat dengan sumber terpercaya, analisis mendalam, dan pencarian real-time.',
    features: ['Unlimited AI Search', 'GPT-4 & Claude 3', 'File Upload (PDF, dll)', 'Advanced Search Filters', 'API Access', 'Priority Processing'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka perplexity.ai\n2. Login akun\n3. Pro aktif otomatis\n4. Mulai riset',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['chatgpt-plus', 'claude-pro'],
  },
  {
    slug: 'microsoft-copilot-pro',
    name: 'Microsoft Copilot', tier: 'Pro',
    category: 'AI Tools', logoText: 'Copilot',
    tile: 'linear-gradient(150deg,#0078d4,#004fa3)',
    description: 'Copilot Pro terintegrasi langsung ke Microsoft 365 — Word, Excel, PowerPoint, Outlook, dan Teams. Tingkatkan produktivitas kerja.',
    features: ['Microsoft 365 Integration', 'GPT-4 Turbo Priority', 'Copilot in Word & Excel', 'Image Creation (DALL·E)', '200+ Boost per Day', 'Early Access Features'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka copilot.microsoft.com\n2. Login akun Microsoft\n3. Aktifkan Pro\n4. Gunakan di Microsoft 365',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['chatgpt-plus', 'gemini-advanced'],
  },
  {
    slug: 'cursor-pro',
    name: 'Cursor', tier: 'Pro',
    category: 'AI Tools', logoText: 'Cursor',
    tile: 'linear-gradient(150deg,#1a1a2e,#060616)',
    description: 'Code editor AI-first. Autocomplete cerdas, chat dengan codebase, dan refactor otomatis. Wajib punya untuk developer modern.',
    features: ['Unlimited Claude 3.5 Sonnet', 'GPT-4o Access', 'AI Chat with Codebase', 'Cursor Tab Autocomplete', 'Unlimited Context', 'Early Access Models'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Install Cursor dari cursor.sh\n2. Login akun yang diberikan\n3. Pro aktif otomatis\n4. Mulai coding',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['github-copilot', 'replit-core'],
  },
  {
    slug: 'github-copilot',
    name: 'GitHub Copilot', tier: 'Pro',
    category: 'AI Tools', logoText: 'Copilot',
    tile: 'linear-gradient(150deg,#24292e,#0d1117)',
    description: 'AI coding assistant dari GitHub. Saran kode real-time, penyelesaian otomatis, dan chat AI langsung di VS Code dan editor favorit.',
    features: ['Code Completion AI', 'Copilot Chat', 'Multi-file Editing', 'VS Code, JetBrains, Vim', 'Security Vulnerability Filter', 'CLI Suggestions'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install GitHub Copilot extension\n2. Login dengan akun GitHub\n3. Copilot aktif di editor\n4. Mulai coding',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['cursor-pro', 'replit-core'],
  },
  {
    slug: 'notion-ai',
    name: 'Notion', tier: 'AI',
    category: 'AI Tools', logoText: 'Notion',
    tile: 'linear-gradient(150deg,#1c1c1e,#000000)',
    description: 'Notion Plus dengan AI terintegrasi. Tulis, rangkum, terjemahkan, dan analisis dokumen langsung dalam workspace Notion kamu.',
    features: ['Notion AI Writing', 'Summarize & Translate', 'Q&A with Documents', 'Unlimited Blocks', 'Unlimited File Uploads', 'Version History'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Login ke notion.so\n2. Masuk ke workspace\n3. Notion AI aktif otomatis\n4. Gunakan di setiap page',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['chatgpt-plus', 'grammarly-premium'],
  },
  {
    slug: 'grammarly-premium',
    name: 'Grammarly', tier: 'Premium',
    category: 'AI Tools', logoText: 'Grammarly',
    tile: 'linear-gradient(150deg,#15c39a,#0a8a6b)',
    description: 'Asisten penulisan AI terbaik. Koreksi grammar, gaya penulisan, plagiarisme, dan tone secara real-time di semua platform.',
    features: ['Advanced Grammar Check', 'Tone Adjustment', 'Plagiarism Detector', 'Style Suggestions', 'Browser Extension', 'MS Word & Google Docs'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install ekstensi Grammarly\n2. Login akun premium\n3. Aktif di browser & editor\n4. Mulai menulis',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['notion-ai', 'chatgpt-plus'],
  },
  {
    slug: 'midjourney',
    name: 'Midjourney', tier: 'Standard',
    category: 'AI Tools', logoText: 'MJ',
    tile: 'linear-gradient(150deg,#1a1a1a,#000000)',
    description: 'Generator gambar AI terbaik dunia. Buat ilustrasi, artwork, foto konsep, dan visual kreatif stunning hanya dengan teks.',
    features: ['15 GPU Hours/Month', 'Unlimited Relaxed Generations', 'Fast Mode Included', 'Discord & Web Access', 'Commercial Usage', 'Upscale & Variation'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Bergabung server Discord\n2. Login dengan akun yang diberikan\n3. Gunakan /imagine command\n4. Nikmati generasi gambar AI',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['leonardo-ai', 'runway-ml', 'canva-pro'],
  },
  {
    slug: 'leonardo-ai',
    name: 'Leonardo', tier: 'AI Pro',
    category: 'AI Tools', logoText: 'Leonardo',
    tile: 'linear-gradient(150deg,#7c3aed,#4c1d95)',
    description: 'Platform AI generatif untuk gambar, video, dan aset game. Buat visual profesional dengan model AI khusus dan kontrol penuh.',
    features: ['2500 Token/Month', 'AI Image Generation', 'Motion Video', 'Canvas Editor', 'Custom Model Training', 'API Access'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka leonardo.ai\n2. Login akun\n3. Token Pro aktif\n4. Mulai generate',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['midjourney', 'runway-ml'],
  },
  {
    slug: 'runway-ml',
    name: 'Runway', tier: 'Standard',
    category: 'AI Tools', logoText: 'Runway',
    tile: 'linear-gradient(150deg,#000000,#1a1a2e)',
    description: 'Studio AI kreatif untuk video. Gen-3 Alpha — buat video sinematik dari teks atau gambar dengan kualitas Hollywood.',
    features: ['125 Credits/Month', 'Gen-3 Alpha Video', 'Image-to-Video', 'Text-to-Video', 'Video Inpainting', '4K Export'],
    plans: plans(35000, 95000, 180000, 340000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka runwayml.com\n2. Login akun Standard\n3. Credits aktif\n4. Buat video AI',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['midjourney', 'leonardo-ai'],
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs', tier: 'Starter',
    category: 'AI Tools', logoText: 'ElevenLabs',
    tile: 'linear-gradient(150deg,#0f172a,#1e293b)',
    description: 'Text-to-speech AI paling realistis. Buat narasi, dubbing, voiceover, dan kloning suara dengan kualitas studio profesional.',
    features: ['30K Chars/Month', '29 Languages', 'Voice Cloning', 'AI Dubbing', 'Projects Studio', 'Commercial License'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka elevenlabs.io\n2. Login akun\n3. Starter aktif\n4. Buat voice',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['runway-ml', 'midjourney'],
  },

  // ── Design ──────────────────────────────────────────────────────────────
  {
    slug: 'canva-pro',
    name: 'Canva', tier: 'Pro',
    category: 'Design',
    logo: '/logos/canva.svg',
    tile: 'linear-gradient(150deg,#1a5cff,#7d2ae7)',
    description: 'Platform desain grafis terlengkap. Ratusan ribu template premium, Brand Kit, Background Remover, dan fitur kolaborasi tim.',
    features: ['100M+ Template Premium', 'Brand Kit', 'Background Remover', '1TB Cloud Storage', 'Content Planner', 'Magic Resize'],
    plans: plans(12500, 33000, 62000, 115000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka canva.com\n2. Login dengan email\n3. Pro aktif otomatis\n4. Akses semua template',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['canva-teams', 'adobe-creative-cloud', 'figma-pro'],
  },
  {
    slug: 'canva-teams',
    name: 'Canva', tier: 'Teams',
    category: 'Design',
    logo: '/logos/canva.svg',
    tile: 'linear-gradient(150deg,#0052cc,#5b21b6)',
    description: 'Canva untuk tim. Kolaborasi real-time, brand management terpusat, dan semua fitur Pro untuk seluruh tim kreatif kamu.',
    features: ['Semua Fitur Pro', 'Real-time Collaboration', 'Brand Controls', 'Template Locking', 'Unlimited Storage', 'Team Reporting'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka canva.com\n2. Login akun Teams\n3. Undang anggota tim\n4. Mulai kolaborasi',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['canva-pro', 'figma-pro'],
  },
  {
    slug: 'adobe-creative-cloud',
    name: 'Adobe Creative Cloud', tier: 'All Apps',
    category: 'Design', logoText: 'Adobe',
    tile: 'linear-gradient(150deg,#e1251b,#8b0000)',
    description: 'Akses semua 20+ aplikasi Adobe sekaligus — Photoshop, Illustrator, Premiere Pro, After Effects, Lightroom, dan masih banyak lagi.',
    features: ['20+ Aplikasi Adobe', '100GB Cloud Storage', 'Adobe Fonts', 'Behance Pro', 'Creative Cloud Libraries', 'Generative AI (Firefly)'],
    plans: plans(45000, 122000, 230000, 430000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['best_seller'],
    activationGuide: '1. Download Adobe Creative Cloud\n2. Login dengan akun yang diberikan\n3. Install aplikasi pilihan\n4. Mulai berkarya',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['photoshop', 'premiere-pro', 'after-effects'],
  },
  {
    slug: 'photoshop',
    name: 'Adobe Photoshop', tier: 'Pro',
    category: 'Design', logoText: 'Ps',
    tile: 'linear-gradient(150deg,#001e36,#003158)',
    description: 'Software editing foto & desain grafis terbaik dunia. Dengan AI Generative Fill, retouching, dan komposisi tak terbatas.',
    features: ['Generative Fill AI', 'Neural Filters', 'Object Selection', 'Remove Tool AI', '100GB Cloud Storage', 'Adobe Firefly'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install Photoshop via Creative Cloud\n2. Login akun Adobe\n3. Aktivasi otomatis\n4. Mulai edit',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['adobe-creative-cloud', 'illustrator', 'lightroom'],
  },
  {
    slug: 'illustrator',
    name: 'Adobe Illustrator', tier: 'Pro',
    category: 'Design', logoText: 'Ai',
    tile: 'linear-gradient(150deg,#ff7c00,#8c3800)',
    description: 'Software desain vektor profesional. Buat logo, ilustrasi, dan grafis skala tanpa batas dengan presisi sempurna.',
    features: ['Generative Recolor AI', 'Vector Network', 'Cloud Documents', 'Adobe Fonts', 'Repeat Objects', '100GB Storage'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install via Creative Cloud\n2. Login akun Adobe\n3. Aktif otomatis\n4. Desain vektor',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['photoshop', 'adobe-creative-cloud'],
  },
  {
    slug: 'premiere-pro',
    name: 'Adobe Premiere Pro', tier: 'Pro',
    category: 'Design', logoText: 'Pr',
    tile: 'linear-gradient(150deg,#00005b,#000f8f)',
    description: 'Editor video profesional pilihan filmmaker & YouTuber. AI Speech Enhancement, Auto Reframe, dan integrasi After Effects.',
    features: ['AI Speech Enhancement', 'Auto Reframe', 'Color Grading Pro', 'Dynamic Link After Effects', 'Remote Collaboration', '100GB Cloud Storage'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['best_seller'],
    activationGuide: '1. Install via Creative Cloud\n2. Login akun Adobe\n3. Aktif otomatis\n4. Edit video',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['after-effects', 'adobe-creative-cloud', 'capcut-pro'],
  },
  {
    slug: 'lightroom',
    name: 'Adobe Lightroom', tier: 'Premium',
    category: 'Design', logoText: 'Lr',
    tile: 'linear-gradient(150deg,#001f3a,#003a6e)',
    description: 'Edit foto profesional di mana saja. Preset premium, AI Denoise, Masking cerdas, dan sinkronisasi cloud lintas perangkat.',
    features: ['AI Denoise', 'AI Masking', '1TB Cloud Storage', 'Preset & Profiles', 'Advanced HDR', 'Mobile Sync'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install Lightroom\n2. Login akun Adobe\n3. Cloud sync aktif\n4. Edit foto',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['photoshop', 'adobe-creative-cloud'],
  },
  {
    slug: 'after-effects',
    name: 'Adobe After Effects', tier: 'Pro',
    category: 'Design', logoText: 'Ae',
    tile: 'linear-gradient(150deg,#00005b,#1a0073)',
    description: 'Software motion graphics & visual effects terdepan. Buat animasi, komposisi VFX, dan title sequence sinematik.',
    features: ['Motion Graphics', 'VFX Compositing', '3D Workspace', 'Dynamic Link Premiere', 'Generative AI', '100GB Storage'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install via Creative Cloud\n2. Login akun Adobe\n3. Aktif otomatis\n4. Buat animasi',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['premiere-pro', 'adobe-creative-cloud'],
  },
  {
    slug: 'figma-pro',
    name: 'Figma', tier: 'Professional',
    category: 'Design', logoText: 'Figma',
    tile: 'linear-gradient(150deg,#f24e1e,#7b2d00)',
    description: 'Platform desain UI/UX kolaboratif. Prototyping interaktif, handoff developer, dan design system all-in-one.',
    features: ['Unlimited Projects', 'Advanced Prototyping', 'Dev Mode', 'Auto Layout', 'Variables & Modes', 'FigJam Included'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka figma.com\n2. Login akun Professional\n3. Aktif otomatis\n4. Mulai desain',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['canva-pro', 'adobe-creative-cloud'],
  },
  {
    slug: 'capcut-pro',
    name: 'CapCut', tier: 'Pro',
    category: 'Design',
    logo: '/logos/capcut.svg', whiteLogo: true,
    tile: 'linear-gradient(150deg,#161821,#04050a)',
    description: 'Editor video all-in-one favoritnya kreator konten. AI Remove Background, Auto Captions, dan template trending TikTok.',
    features: ['AI Auto Captions', 'Remove Background', '4K Export', 'Trending Templates', 'AI Effects', 'No Watermark'],
    plans: plans(13500, 36000, 68000, 128000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka CapCut\n2. Login akun Pro\n3. Semua fitur terbuka\n4. Edit video',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['invideo-ai', 'premiere-pro'],
  },
  {
    slug: 'invideo-ai',
    name: 'InVideo', tier: 'AI Max',
    category: 'Design', logoText: 'InVideo',
    tile: 'linear-gradient(150deg,#5046e5,#2d2889)',
    description: 'Buat video dari teks dengan AI. Ribuan template, AI voiceover, dan ekspor berkualitas tinggi dalam hitungan menit.',
    features: ['AI Video from Text', '10M+ Media Library', 'AI Voiceover', 'Brand Preset', '4K Export', 'Team Collaboration'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka invideo.io\n2. Login akun Max\n3. Aktif otomatis\n4. Buat video',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['capcut-pro', 'runway-ml'],
  },
  {
    slug: 'envato-elements',
    name: 'Envato Elements', tier: 'Pro',
    category: 'Design', logoText: 'Envato',
    tile: 'linear-gradient(150deg,#82b541,#4a6e1e)',
    description: 'Unduhan aset kreatif tak terbatas. Template, font, gambar stok, plugin, musik, dan lainnya — semua dalam satu langganan.',
    features: ['Unlimited Downloads', '1M+ Creative Assets', 'Stock Photos & Videos', 'Fonts & Plugins', 'Music & SFX', 'Commercial License'],
    plans: plans(30000, 81000, 154000, 288000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka elements.envato.com\n2. Login akun Pro\n3. Unduh aset bebas\n4. Gunakan untuk proyek',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['freepik-premium', 'shutterstock'],
  },
  {
    slug: 'freepik-premium',
    name: 'Freepik', tier: 'Premium',
    category: 'Design', logoText: 'Freepik',
    tile: 'linear-gradient(150deg,#1273eb,#0a4da0)',
    description: 'Jutaan aset grafis premium — vektor, foto, PSD, template, dan ikon berkualitas tinggi tanpa batas unduhan.',
    features: ['Unlimited Downloads', '50M+ Assets', 'No Attribution Required', 'AI Image Generator', 'HD & 4K Assets', 'Commercial License'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka freepik.com\n2. Login akun Premium\n3. Unduh bebas\n4. Gunakan tanpa atribusi',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['envato-elements', 'shutterstock'],
  },
  {
    slug: 'shutterstock',
    name: 'Shutterstock', tier: 'Standard',
    category: 'Design', logoText: 'Shutterstock',
    tile: 'linear-gradient(150deg,#ee3124,#8b0000)',
    description: 'Foto stok, video, dan musik berlisensi premium. Jutaan konten profesional siap pakai untuk proyek komersial.',
    features: ['350M+ Stock Photos', 'Video & Music Clips', 'AI Image Generator', 'Editorial Content', 'Standard License', 'API Access'],
    plans: plans(35000, 95000, 180000, 340000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka shutterstock.com\n2. Login akun Standard\n3. Download bebas\n4. Gunakan untuk klien',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['envato-elements', 'freepik-premium'],
  },
  {
    slug: 'motion-array',
    name: 'Motion Array', tier: 'Pro',
    category: 'Design', logoText: 'MotionArray',
    tile: 'linear-gradient(150deg,#1a1a2e,#060611)',
    description: 'Platform template video & plugin kreatif. Ribuan template Premiere Pro, After Effects, dan Final Cut siap pakai.',
    features: ['Unlimited Downloads', 'Premiere Pro Templates', 'After Effects Templates', 'LUTs & Presets', 'Stock Footage', 'Reviewer Tool'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka motionarray.com\n2. Login akun Pro\n3. Download template\n4. Impor ke editor',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['envato-elements', 'premiere-pro'],
  },
  {
    slug: 'placeit',
    name: 'Placeit', tier: 'Unlimited',
    category: 'Design', logoText: 'Placeit',
    tile: 'linear-gradient(150deg,#6e45e1,#3b1fa8)',
    description: 'Buat mockup, logo, video, dan template desain langsung di browser. Ratusan ribu aset siap pakai untuk branding.',
    features: ['Unlimited Mockups', 'Logo Maker', 'Video Templates', 'Social Media Templates', 'Merch Design', 'Commercial License'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka placeit.net\n2. Login akun Unlimited\n3. Buat desain\n4. Download langsung',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['canva-pro', 'envato-elements'],
  },

  // ── Streaming ────────────────────────────────────────────────────────────
  {
    slug: 'netflix-premium',
    name: 'Netflix', tier: 'Premium',
    category: 'Streaming',
    logo: '/logos/netflix.svg',
    tile: 'linear-gradient(150deg,#1b0508,#000000)',
    description: 'Ribuan film, serial TV, anime, dan konten eksklusif Netflix Originals dalam kualitas Ultra HD 4K dengan Dolby Atmos.',
    features: ['Ultra HD 4K + HDR', 'Dolby Atmos', 'Download Offline', '4 Layar Sekaligus', 'Profil Sendiri', 'Konten Eksklusif Netflix'],
    plans: plans(16500, 44000, 83000, 155000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka netflix.com\n2. Login dengan akun\n3. Buat profil sendiri\n4. Nikmati streaming',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['disney-plus', 'hbo-max', 'prime-video'],
  },
  {
    slug: 'disney-plus',
    name: 'Disney+', tier: 'Premium',
    category: 'Streaming',
    logo: '/logos/disney-plus.svg', whiteLogo: true,
    tile: 'linear-gradient(150deg,#0a1a4d,#050b22)',
    description: 'Disney, Marvel, Star Wars, National Geographic, dan Pixar dalam satu platform. Konten eksklusif terbaik keluarga.',
    features: ['4K Ultra HD', 'Dolby Vision & Atmos', 'Download Offline', 'Profil Anak Terpisah', 'Konten Eksklusif', 'Live Events'],
    plans: plans(15500, 42000, 80000, 148000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka disneyplus.com\n2. Login akun\n3. Atur profil\n4. Mulai nonton',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'hbo-max'],
  },
  {
    slug: 'prime-video',
    name: 'Prime Video', tier: 'Premium',
    category: 'Streaming',
    logo: '/logos/prime-video.svg',
    tile: 'linear-gradient(150deg,#0a2233,#050b18)',
    description: 'Konten orisinal Amazon Studios, The Boys, Rings of Power, dan ribuan film & serial dalam kualitas 4K HDR.',
    features: ['4K Ultra HD + HDR', 'Download Offline', 'X-Ray Feature', 'Channels Add-on', 'Live Sports', 'Watch Party'],
    plans: plans(14500, 39000, 74000, 138000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka primevideo.com\n2. Login akun\n3. Watch langsung\n4. Download untuk offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'disney-plus'],
  },
  {
    slug: 'hbo-max',
    name: 'Max (HBO)', tier: 'Ultimate',
    category: 'Streaming', logoText: 'MAX',
    tile: 'linear-gradient(150deg,#6700c7,#370069)',
    description: 'HBO, Warner Bros., DC Universe, dan Max Originals. Game of Thrones, House of the Dragon, dan konten premium Warner.',
    features: ['4K Ultra HD', 'Dolby Vision & Atmos', '3 Layar Serentak', 'Download Offline', 'IMAX Enhanced', 'HBO Original Series'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka max.com\n2. Login akun\n3. Ultimate aktif\n4. Streaming 4K',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'disney-plus'],
  },
  {
    slug: 'apple-tv-plus',
    name: 'Apple TV+', tier: 'Premium',
    category: 'Streaming', logoText: 'Apple TV+',
    tile: 'linear-gradient(150deg,#1c1c1e,#000000)',
    description: 'Konten orisinal Apple — Ted Lasso, Severance, The Morning Show. Kualitas sinematik tertinggi tanpa iklan.',
    features: ['4K HDR Dolby Vision', 'Dolby Atmos', 'Apple Originals', 'Tanpa Iklan', 'Offline Download', 'Shareplay'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka tv.apple.com\n2. Login Apple ID\n3. Akses konten langsung\n4. Download offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'disney-plus'],
  },
  {
    slug: 'crunchyroll',
    name: 'Crunchyroll', tier: 'Mega Fan',
    category: 'Streaming', logoText: 'Crunchyroll',
    tile: 'linear-gradient(150deg,#f47521,#8b3e00)',
    description: 'Platform streaming anime terbesar di dunia. Tonton simulcast anime terbaru langsung dari Jepang dalam kualitas HD.',
    features: ['1200+ Anime Series', 'HD & 4K Streaming', 'Simulcast dari Jepang', '4 Layar Serentak', 'Offline Download', 'Manga Library'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka crunchyroll.com\n2. Login akun Mega Fan\n3. Akses anime\n4. Nonton tanpa iklan',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'disney-plus'],
  },
  {
    slug: 'viu-premium',
    name: 'Viu', tier: 'Premium',
    category: 'Streaming', logoText: 'Viu',
    tile: 'linear-gradient(150deg,#ffcc00,#b38900)',
    description: 'Drama Korea, Asia, dan konten lokal terlengkap. Update terbaru, subtitle Indonesia, dan streaming HD tanpa iklan.',
    features: ['Drama Korea Terbaru', 'Update Simultan', 'Subtitle Indonesia', 'HD Streaming', 'Download Offline', 'Multi Device'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka viu.com\n2. Login akun Premium\n3. Tonton drama Korea\n4. Download offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'wetv-vip'],
  },
  {
    slug: 'vidio-platinum',
    name: 'Vidio', tier: 'Platinum',
    category: 'Streaming', logoText: 'Vidio',
    tile: 'linear-gradient(150deg,#0078ff,#0052b3)',
    description: 'Platform streaming lokal terlengkap — Liga Indonesia, Series Original, film Indonesia, dan siaran TV nasional.',
    features: ['Liga Indonesia Langsung', 'Series Original Vidio', 'Film Indonesia', 'TV Nasional Live', 'FHD Streaming', 'Multi Device'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka vidio.com\n2. Login akun Platinum\n3. Tonton konten\n4. Live streaming langsung',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['viu-premium', 'netflix-premium'],
  },
  {
    slug: 'wetv-vip',
    name: 'WeTV', tier: 'VIP',
    category: 'Streaming', logoText: 'WeTV',
    tile: 'linear-gradient(150deg,#00b050,#005a28)',
    description: 'Drama China, Korea, Thailand terlengkap. Update cepat, subtitle Indonesia, dan streaming FHD tanpa gangguan.',
    features: ['Drama Asia Terlengkap', 'Update Cepat', 'Subtitle Indonesia', 'FHD Streaming', 'Download Offline', 'Akses Eksklusif'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka wetv.vip\n2. Login akun VIP\n3. Tonton drama Asia\n4. Download favorit',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['viu-premium', 'iqiyi-vip'],
  },
  {
    slug: 'iqiyi-vip',
    name: 'iQIYI', tier: 'VIP',
    category: 'Streaming', logoText: 'iQIYI',
    tile: 'linear-gradient(150deg,#00aa45,#006028)',
    description: 'Platform streaming China terbesar. Drama, variety show, dan konten eksklusif iQIYI Original dalam kualitas 4K.',
    features: ['4K Streaming', 'Konten Eksklusif', 'Drama China Terlengkap', 'Download Offline', 'Subtitle Indonesia', 'Multi Device'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka iq.com\n2. Login akun VIP\n3. Tonton konten\n4. Download offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['wetv-vip', 'viu-premium'],
  },
  {
    slug: 'mubi',
    name: 'MUBI', tier: 'Premium',
    category: 'Streaming', logoText: 'MUBI',
    tile: 'linear-gradient(150deg,#1a1a1a,#000000)',
    description: 'Platform film art-house dan sinema dunia terkurasi. Film festival internasional, klasik sinema, dan arthouse terbaik.',
    features: ['Film Terkurasi Pakar', 'Film Festival Dunia', 'Klasik Sinema', 'Tanpa Iklan', 'Download Offline', 'Komentar Kurator'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka mubi.com\n2. Login akun\n3. Tonton film terkurasi\n4. Download untuk offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'apple-tv-plus'],
  },
  {
    slug: 'hulu',
    name: 'Hulu', tier: 'No Ads',
    category: 'Streaming', logoText: 'Hulu',
    tile: 'linear-gradient(150deg,#1ce783,#0c8048)',
    description: 'Streaming film, serial, dan live TV terbesar di AS. Konten eksklusif Hulu Originals tanpa gangguan iklan.',
    features: ['Hulu Originals', 'Current Season TV', 'Live TV Option', 'Tanpa Iklan', 'Download Offline', '4K Streaming'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka hulu.com\n2. Login akun No Ads\n3. Streaming langsung\n4. Download favorit',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['netflix-premium', 'hbo-max'],
  },

  // ── Music ────────────────────────────────────────────────────────────────
  {
    slug: 'spotify-premium',
    name: 'Spotify', tier: 'Premium',
    category: 'Music',
    logo: '/logos/spotify.svg',
    tile: 'linear-gradient(150deg,#0d2a17,#06120c)',
    description: 'Streaming musik terbesar di dunia. 100 juta lagu, podcast eksklusif, dan playlist AI-generated tanpa iklan.',
    features: ['100M+ Lagu & Podcast', 'Audio Kualitas Tinggi', 'Download Offline', 'Tanpa Iklan', 'Crossfade & EQ', 'Spotify AI DJ'],
    plans: plans(10500, 28000, 53000, 100000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka spotify.com\n2. Login akun Premium\n3. Nikmati tanpa iklan\n4. Download offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['youtube-premium', 'apple-music'],
  },
  {
    slug: 'youtube-premium',
    name: 'YouTube', tier: 'Premium',
    category: 'Music', logoText: 'YouTube',
    tile: 'linear-gradient(150deg,#ff0000,#8b0000)',
    description: 'YouTube tanpa iklan + YouTube Music. Background play, download offline, dan akses YouTube Originals eksklusif.',
    features: ['YouTube Tanpa Iklan', 'Background Play', 'Download Offline', 'YouTube Music', 'YouTube Originals', 'Picture-in-Picture'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Login Google\n2. Aktifkan Premium\n3. Nikmati tanpa iklan\n4. Background play aktif',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['spotify-premium', 'apple-music'],
  },
  {
    slug: 'apple-music',
    name: 'Apple Music', tier: 'Individual',
    category: 'Music', logoText: 'Apple Music',
    tile: 'linear-gradient(150deg,#fc3c44,#8b0000)',
    description: 'Lossless Audio & Dolby Atmos Spatial Audio. 100 juta lagu dalam kualitas studio — pengalaman mendengarkan terbaik.',
    features: ['Lossless Audio Hi-Res', 'Dolby Atmos Spatial', '100M+ Lagu', 'Radio Live 24/7', 'Download Offline', 'Apple Watch Sync'],
    plans: plans(10500, 28000, 53000, 100000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka Apple Music\n2. Login Apple ID\n3. Lossless aktif\n4. Dengarkan offline',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['spotify-premium', 'youtube-premium'],
  },
  {
    slug: 'youtube-music',
    name: 'YouTube Music', tier: 'Premium',
    category: 'Music', logoText: 'YT Music',
    tile: 'linear-gradient(150deg,#cc0000,#700000)',
    description: 'Streaming musik dari Google. Rekomendasi cerdas berbasis riwayat YouTube, background play, dan download offline.',
    features: ['Rekomendasi AI Smart', 'Background Play', 'Download Offline', 'Live Versions', 'Tanpa Iklan', 'Lyrics Real-time'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka YouTube Music\n2. Login akun\n3. Premium aktif\n4. Play background',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['spotify-premium', 'youtube-premium'],
  },
  {
    slug: 'deezer',
    name: 'Deezer', tier: 'Premium',
    category: 'Music', logoText: 'Deezer',
    tile: 'linear-gradient(150deg,#ef5466,#b01225)',
    description: 'Platform musik dengan Flow — playlist AI personal yang belajar dari kebiasaan dengarmu. HiFi quality tersedia.',
    features: ['90M+ Lagu', 'Deezer Flow AI', 'HiFi Lossless', 'Download Offline', 'Lyrics Real-time', 'Podcast & Radio'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka deezer.com\n2. Login akun Premium\n3. Flow aktif\n4. Download musik',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['spotify-premium', 'tidal'],
  },
  {
    slug: 'tidal',
    name: 'Tidal', tier: 'HiFi Plus',
    category: 'Music', logoText: 'TIDAL',
    tile: 'linear-gradient(150deg,#1a1a1a,#000000)',
    description: 'Kualitas audio tertinggi di industri. Master Quality Authenticated, Dolby Atmos, 360 Reality Audio — untuk audiophile.',
    features: ['MQA Master Quality', 'Dolby Atmos Music', '360 Reality Audio', '100M+ Lagu', 'Exclusive Releases', 'Artist Connect'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka tidal.com\n2. Login akun HiFi Plus\n3. Atur kualitas audio\n4. Nikmati Master Quality',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['apple-music', 'spotify-premium'],
  },
  {
    slug: 'joox-vip',
    name: 'JOOX', tier: 'VIP',
    category: 'Music', logoText: 'JOOX',
    tile: 'linear-gradient(150deg,#ff4e1c,#8b1c00)',
    description: 'Platform musik Asia terpopuler. Lagu Indonesia, K-Pop, C-Pop, dan karaoke mode favorit di Indonesia.',
    features: ['Lagu Indonesia Terlengkap', 'Karaoke Mode', 'Offline Download', 'Tanpa Iklan', 'HiFi Quality', 'Lyrics Sync'],
    plans: plans(8000, 21000, 40000, 75000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka JOOX\n2. Login akun VIP\n3. Download lagu\n4. Karaoke mode aktif',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['spotify-premium', 'youtube-music'],
  },
  {
    slug: 'soundcloud-go',
    name: 'SoundCloud', tier: 'Go+',
    category: 'Music', logoText: 'SoundCloud',
    tile: 'linear-gradient(150deg,#ff5500,#b33000)',
    description: 'Platform musik indie & underground terbesar. Akses 300 juta track dari artis indie, DJ, dan produser seluruh dunia.',
    features: ['300M+ Tracks', 'Offline Listening', 'HQ Audio', 'Tanpa Iklan', 'Exclusive Tracks', 'DJ Mixes'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka soundcloud.com\n2. Login akun Go+\n3. Offline aktif\n4. Dengarkan indie music',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['spotify-premium', 'tidal'],
  },

  // ── Learning ─────────────────────────────────────────────────────────────
  {
    slug: 'coursera-plus',
    name: 'Coursera', tier: 'Plus',
    category: 'Learning', logoText: 'Coursera',
    tile: 'linear-gradient(150deg,#0056d2,#003888)',
    description: 'Akses tak terbatas ke 7000+ kursus dari universitas top dunia — Google, IBM, Meta, Yale, Stanford. Sertifikat profesional.',
    features: ['7000+ Kursus Premium', 'Sertifikat Diakui', 'Universitas Top Dunia', 'Google & IBM Certs', 'Guided Projects', 'No Time Limit'],
    plans: plans(35000, 95000, 180000, 340000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka coursera.org\n2. Login akun Plus\n3. Daftar kursus apapun\n4. Ikuti pembelajaran',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['udemy-business', 'linkedin-learning'],
  },
  {
    slug: 'udemy-business',
    name: 'Udemy', tier: 'Business',
    category: 'Learning', logoText: 'Udemy',
    tile: 'linear-gradient(150deg,#ec5252,#8b0000)',
    description: 'Akses lebih dari 22.000 kursus pilihan Udemy Business — programming, data science, design, dan leadership untuk profesional.',
    features: ['22K+ Kursus Business', 'Sertifikat Penyelesaian', 'Download untuk Offline', 'Subtitles Multi Bahasa', 'Progress Tracking', 'Mobile & Desktop'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka udemy.com\n2. Login akun Business\n3. Browse kursus\n4. Mulai belajar',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['coursera-plus', 'skillshare'],
  },
  {
    slug: 'skillshare',
    name: 'Skillshare', tier: 'Premium',
    category: 'Learning', logoText: 'Skillshare',
    tile: 'linear-gradient(150deg,#002333,#000d13)',
    description: 'Platform kreativitas online. Desain, ilustrasi, fotografi, animasi, bisnis — belajar dari para profesional industri.',
    features: ['40K+ Kelas Kreatif', 'Tanpa Iklan', 'Project-based Learning', 'Offline Download', 'Komunitas Aktif', 'Sertifikat Kelas'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka skillshare.com\n2. Login akun\n3. Pilih kelas kreatif\n4. Mulai belajar',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['udemy-business', 'coursera-plus'],
  },
  {
    slug: 'masterclass',
    name: 'MasterClass', tier: 'Plus',
    category: 'Learning', logoText: 'MasterClass',
    tile: 'linear-gradient(150deg,#1a1a1a,#000000)',
    description: 'Belajar dari para maestro dunia — Gordon Ramsay, Natalie Portman, Martin Scorsese, Serena Williams, dan ratusan lagi.',
    features: ['180+ Kelas Master', 'Sinematografi Kelas Dunia', 'Offline Download', 'Workbook & Lesson Plans', 'Community Hub', '2 Akun Household'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka masterclass.com\n2. Login akun Plus\n3. Pilih instruktur\n4. Tonton kelas',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['skillshare', 'coursera-plus'],
  },
  {
    slug: 'brilliant',
    name: 'Brilliant', tier: 'Premium',
    category: 'Learning', logoText: 'Brilliant',
    tile: 'linear-gradient(150deg,#f15a24,#8b2500)',
    description: 'Belajar matematika, sains, dan computer science melalui problem-solving interaktif. Pendekatan hands-on yang terbukti efektif.',
    features: ['Math, Science & CS', 'Interactive Problems', 'AI Learning Paths', 'Offline Mode', '60+ Courses', 'Mobile & Web'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka brilliant.org\n2. Login akun Premium\n3. Pilih topik\n4. Belajar interaktif',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['codecademy-pro', 'coursera-plus'],
  },
  {
    slug: 'codecademy-pro',
    name: 'Codecademy', tier: 'Pro',
    category: 'Learning', logoText: 'Codecademy',
    tile: 'linear-gradient(150deg,#1f4056,#0a1c26)',
    description: 'Belajar coding interaktif. Python, JavaScript, SQL, Web Dev, Data Science — dengan kurikulum terstruktur dan proyek nyata.',
    features: ['100+ Kursus Coding', 'Projects Nyata', 'Career Paths', 'Code Review AI', 'Sertifikat Profesi', 'Interview Prep'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka codecademy.com\n2. Login akun Pro\n3. Pilih career path\n4. Mulai coding',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['brilliant', 'coursera-plus'],
  },
  {
    slug: 'duolingo-super',
    name: 'Duolingo', tier: 'Super',
    category: 'Learning', logoText: 'Duolingo',
    tile: 'linear-gradient(150deg,#58cc02,#2e6e00)',
    description: 'Belajar bahasa tanpa batas — Inggris, Mandarin, Spanyol, Jepang, dan 40+ bahasa lain. Tanpa iklan, unlimited hearts.',
    features: ['40+ Bahasa', 'Unlimited Hearts', 'Tanpa Iklan', 'Offline Mode', 'Personalized Practice', 'Progress Reports'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka Duolingo\n2. Login akun Super\n3. Pilih bahasa\n4. Mulai belajar',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['babbel', 'coursera-plus'],
  },
  {
    slug: 'linkedin-learning',
    name: 'LinkedIn Learning', tier: 'Premium',
    category: 'Learning', logoText: 'LinkedIn',
    tile: 'linear-gradient(150deg,#0073b1,#004876)',
    description: 'Platform learning dari LinkedIn. 21.000+ kursus bisnis, teknologi, dan kreativitas — terintegrasi langsung ke profil LinkedIn.',
    features: ['21K+ Kursus', 'Sertifikat ke LinkedIn', 'Learning Paths', 'Offline Mobile', 'Expert Instructors', 'Business Skills'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka linkedin.com/learning\n2. Login akun Premium\n3. Pilih kursus\n4. Selesaikan & raih sertifikat',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['coursera-plus', 'udemy-business'],
  },
  {
    slug: 'babbel',
    name: 'Babbel', tier: 'Lifetime',
    category: 'Learning', logoText: 'Babbel',
    tile: 'linear-gradient(150deg,#55c87c,#2e7045)',
    description: 'Belajar bahasa dengan metode linguistik terbukti. Inggris, Spanyol, Jerman, Prancis — kurikulum berbasis sains.',
    features: ['14 Bahasa', 'Metode Linguistik Terbukti', 'Speech Recognition', 'Review Tools', 'Offline Lessons', 'Cultural Notes'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka babbel.com\n2. Login akun\n3. Pilih bahasa target\n4. Mulai pelajaran',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['duolingo-super', 'coursera-plus'],
  },

  // ── Cloud ────────────────────────────────────────────────────────────────
  {
    slug: 'google-one',
    name: 'Google One', tier: '100GB',
    category: 'Cloud', logoText: 'Google One',
    tile: 'linear-gradient(150deg,#4285f4,#0d47a1)',
    description: 'Perluas penyimpanan Google hingga 100GB. Backup otomatis foto, Gmail, Drive, dan berbagi dengan anggota keluarga.',
    features: ['100GB Penyimpanan', 'Google Photos Backup', 'Berbagi dengan Keluarga', 'Google VPN', 'Priority Support', 'Extra Member Benefits'],
    plans: plans(8000, 21000, 40000, 75000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka one.google.com\n2. Login akun Google\n3. Upgrade 100GB\n4. Backup otomatis',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['microsoft-365', 'dropbox-plus'],
  },
  {
    slug: 'microsoft-365',
    name: 'Microsoft 365', tier: 'Personal',
    category: 'Cloud', logoText: 'M365',
    tile: 'linear-gradient(150deg,#d83b01,#741e00)',
    description: 'Word, Excel, PowerPoint, Outlook, Teams, dan 1TB OneDrive. Suite produktivitas lengkap Microsoft untuk profesional.',
    features: ['Word, Excel, PowerPoint', '1TB OneDrive', 'Outlook Premium', 'Teams Personal', 'Offline & Online', 'PC, Mac & Mobile'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka office.com\n2. Login akun Microsoft 365\n3. Install aplikasi Office\n4. Gunakan di semua perangkat',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['google-one', 'dropbox-plus'],
  },
  {
    slug: 'dropbox-plus',
    name: 'Dropbox', tier: 'Plus',
    category: 'Cloud', logoText: 'Dropbox',
    tile: 'linear-gradient(150deg,#0061ff,#003b99)',
    description: '2TB cloud storage dengan sinkronisasi canggih. Smart Sync, Paper collaboration, dan version history 180 hari.',
    features: ['2TB Penyimpanan', 'Smart Sync', 'Version History 180 Hari', 'Dropbox Paper', 'Offline Access', 'Priority Support'],
    plans: plans(25000, 68000, 128000, 240000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka dropbox.com\n2. Login akun Plus\n3. Sync aktif\n4. Upload file',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['google-one', 'microsoft-365', 'mega-pro'],
  },
  {
    slug: 'icloud-plus',
    name: 'iCloud+', tier: '200GB',
    category: 'Cloud', logoText: 'iCloud',
    tile: 'linear-gradient(150deg,#0a84ff,#0051a8)',
    description: '200GB iCloud+ dengan Private Relay, Hide My Email, dan HomeKit Secure Video. Ekosistem Apple yang seamless.',
    features: ['200GB Penyimpanan', 'iCloud Private Relay', 'Hide My Email', 'HomeKit Secure Video', 'Berbagi Keluarga', 'End-to-End Encryption'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka iCloud Settings\n2. Login Apple ID\n3. Upgrade 200GB\n4. Sync otomatis',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['google-one', 'dropbox-plus'],
  },
  {
    slug: 'mega-pro',
    name: 'MEGA', tier: 'Pro Lite',
    category: 'Cloud', logoText: 'MEGA',
    tile: 'linear-gradient(150deg,#d9272e,#7a0b0e)',
    description: '400GB cloud storage dengan enkripsi end-to-end. Privasi tertinggi — bahkan MEGA tidak bisa baca file kamu.',
    features: ['400GB Penyimpanan', 'End-to-End Encryption', 'Transfer 1TB/Bulan', 'MEGA Chat Terenkripsi', 'Desktop Sync', 'Mobile App'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka mega.io\n2. Login akun Pro Lite\n3. Upload file\n4. Share securely',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['dropbox-plus', 'google-one'],
  },
  {
    slug: 'pcloud',
    name: 'pCloud', tier: 'Premium',
    category: 'Cloud', logoText: 'pCloud',
    tile: 'linear-gradient(150deg,#09a0e5,#055d84)',
    description: 'Cloud storage Swiss dengan enkripsi tinggi. 2TB storage, file versioning, dan berbagi link yang aman.',
    features: ['2TB Storage', 'Client-side Encryption', 'File Versioning 180 Hari', 'Video Streaming', 'Collaboration Tools', 'EU Data Center'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka pcloud.com\n2. Login akun Premium\n3. Install client\n4. Sync file',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['mega-pro', 'dropbox-plus'],
  },
  {
    slug: 'sync-com',
    name: 'Sync.com', tier: 'Pro Solo',
    category: 'Cloud', logoText: 'Sync',
    tile: 'linear-gradient(150deg,#0071e3,#003f80)',
    description: 'Cloud storage Kanada dengan zero-knowledge encryption. HIPAA compliant, GDPR compliant — untuk data sensitif.',
    features: ['2TB Penyimpanan', 'Zero-Knowledge Encryption', 'Versioning 365 Hari', 'HIPAA & GDPR', 'Shared Folders', 'Remote Wipe'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka sync.com\n2. Login Pro Solo\n3. Install desktop app\n4. Sync file aman',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['pcloud', 'mega-pro'],
  },

  // ── VPN & Security ───────────────────────────────────────────────────────
  {
    slug: 'nordvpn',
    name: 'NordVPN', tier: 'Plus',
    category: 'VPN & Security', logoText: 'NordVPN',
    tile: 'linear-gradient(150deg,#4687ff,#1a3a8f)',
    description: 'VPN tercepat dan paling aman di dunia. 6300+ server di 111 negara, NordLynx protocol, dan perlindungan lengkap.',
    features: ['6300+ Server Global', 'NordLynx Protocol', 'Double VPN', 'Threat Protection', 'No-Logs Policy', '6 Perangkat'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Install NordVPN\n2. Login akun Plus\n3. Pilih server\n4. Koneksi aman',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['expressvpn', 'surfshark'],
  },
  {
    slug: 'expressvpn',
    name: 'ExpressVPN', tier: 'Pro',
    category: 'VPN & Security', logoText: 'ExpressVPN',
    tile: 'linear-gradient(150deg,#da3940,#8b0e12)',
    description: 'VPN premium tercepat dengan Lightway protocol proprietary. 160+ lokasi, split tunneling, dan MediaStreamer DNS.',
    features: ['160+ Lokasi', 'Lightway Protocol', 'Split Tunneling', 'MediaStreamer DNS', 'No-Logs Audited', '8 Perangkat'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install ExpressVPN\n2. Login & aktifkan\n3. Pilih lokasi\n4. Satu klik connect',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['nordvpn', 'surfshark'],
  },
  {
    slug: 'surfshark',
    name: 'Surfshark', tier: 'One',
    category: 'VPN & Security', logoText: 'Surfshark',
    tile: 'linear-gradient(150deg,#1cccba,#0a7a70)',
    description: 'VPN unlimited perangkat. Surfshark One mencakup VPN, Antivirus, Alert, dan Search dalam satu paket terjangkau.',
    features: ['Unlimited Perangkat', 'Antivirus Included', 'Alert Breach Detector', 'CleanWeb Adblocker', 'NoBorders Mode', '100+ Negara'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Install Surfshark\n2. Login akun One\n3. Semua fitur aktif\n4. Connect VPN',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['nordvpn', 'expressvpn'],
  },
  {
    slug: 'proton-vpn',
    name: 'Proton VPN', tier: 'Plus',
    category: 'VPN & Security', logoText: 'ProtonVPN',
    tile: 'linear-gradient(150deg,#6d4aff,#3a1fa8)',
    description: 'VPN dari Swiss yang dikembangkan oleh tim CERN. Tidak ada log, open-source, dan Secure Core architecture.',
    features: ['Secure Core Servers', 'Open Source', 'No-Logs Swiss', 'Stealth Protocol', 'NetShield Adblocker', '10 Perangkat'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install Proton VPN\n2. Login akun Plus\n3. Pilih Secure Core\n4. Connect',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['nordvpn', 'surfshark'],
  },
  {
    slug: 'bitdefender',
    name: 'Bitdefender', tier: 'Total Security',
    category: 'VPN & Security', logoText: 'Bitdefender',
    tile: 'linear-gradient(150deg,#ed1c24,#7a0008)',
    description: 'Perlindungan lengkap — antivirus, VPN 200MB/hari, anti-ransomware, parental control, dan Web Advisor untuk 5 perangkat.',
    features: ['Real-time Antivirus', 'Anti-Ransomware', 'VPN 200MB/Hari', 'Parental Controls', 'Web Advisor', '5 Perangkat'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Download Bitdefender\n2. Login & aktivasi\n3. Scan awal\n4. Proteksi aktif',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['kaspersky', 'malwarebytes'],
  },
  {
    slug: 'kaspersky',
    name: 'Kaspersky', tier: 'Plus',
    category: 'VPN & Security', logoText: 'Kaspersky',
    tile: 'linear-gradient(150deg,#006d5b,#003a30)',
    description: 'Antivirus terdepan dengan deteksi ancaman tertinggi. VPN unlimited, Password Manager, dan Safe Browsing.',
    features: ['Real-time Protection', 'VPN Unlimited', 'Password Manager', 'Safe Money', 'Data Leak Checker', '3 Perangkat'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install Kaspersky\n2. Login akun Plus\n3. Aktivasi lisensi\n4. Scan perangkat',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['bitdefender', 'malwarebytes'],
  },
  {
    slug: 'malwarebytes',
    name: 'Malwarebytes', tier: 'Premium',
    category: 'VPN & Security', logoText: 'Malwarebytes',
    tile: 'linear-gradient(150deg,#003087,#001544)',
    description: 'Antimalware terpercaya. Deteksi dan hapus malware, ransomware, spyware, adware — perlindungan real-time 24/7.',
    features: ['Real-time Malware Detection', 'Anti-Ransomware', 'Browser Guard', 'Scheduled Scans', 'Play Mode', '5 Perangkat'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Install Malwarebytes\n2. Login akun Premium\n3. Aktifkan perlindungan\n4. Jalankan scan',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['bitdefender', 'kaspersky'],
  },

  // ── Developer ─────────────────────────────────────────────────────────────
  {
    slug: 'replit-core',
    name: 'Replit', tier: 'Core',
    category: 'Developer', logoText: 'Replit',
    tile: 'linear-gradient(150deg,#f5821f,#8b3900)',
    description: 'Cloud IDE all-in-one dengan AI Ghostwriter. Deploy, collaborate, dan build aplikasi langsung dari browser.',
    features: ['AI Ghostwriter', '64GB RAM', 'Custom Domains', 'Unlimited Repls', 'Always-On Deployments', 'Private Repls'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['new', 'instant'],
    activationGuide: '1. Buka replit.com\n2. Login akun Core\n3. Semua fitur aktif\n4. Mulai build',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['github-copilot', 'cursor-pro', 'vercel-pro'],
  },
  {
    slug: 'vercel-pro',
    name: 'Vercel', tier: 'Pro',
    category: 'Developer', logoText: 'Vercel',
    tile: 'linear-gradient(150deg,#1a1a1a,#000000)',
    description: 'Platform deploy frontend tercepat. Edge Network global, analytics, preview deployments, dan integrasi CI/CD otomatis.',
    features: ['Bandwidth 1TB', 'Preview Deployments', 'Web Analytics', 'Edge Config', 'Custom Domains', 'Team Collaboration'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka vercel.com\n2. Login akun Pro\n3. Import repo\n4. Deploy otomatis',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['replit-core', 'cloudflare-pro'],
  },
  {
    slug: 'digitalocean',
    name: 'DigitalOcean', tier: 'Pro',
    category: 'Developer', logoText: 'DigitalOcean',
    tile: 'linear-gradient(150deg,#0080ff,#0040a0)',
    description: 'Cloud hosting developer-friendly. Droplets, Kubernetes, App Platform, database managed — semua dalam satu platform.',
    features: ['$50 Credit', 'Droplets SSD', 'Managed Databases', 'Kubernetes', 'App Platform', 'Object Storage'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka digitalocean.com\n2. Login akun\n3. Credit aktif\n4. Deploy server',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['vercel-pro', 'cloudflare-pro'],
  },
  {
    slug: 'cloudflare-pro',
    name: 'Cloudflare', tier: 'Pro',
    category: 'Developer', logoText: 'Cloudflare',
    tile: 'linear-gradient(150deg,#f6821f,#8b3e00)',
    description: 'CDN, DDoS protection, dan Web Application Firewall kelas enterprise untuk website kamu. Performance & security terdepan.',
    features: ['CDN Global', 'DDoS Protection', 'Web Firewall (WAF)', 'Image Optimization', 'Bot Management', 'Analytics Pro'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka cloudflare.com\n2. Login akun Pro\n3. Tambahkan domain\n4. CDN aktif',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['vercel-pro', 'digitalocean'],
  },

  // ── Communication ────────────────────────────────────────────────────────
  {
    slug: 'zoom-pro',
    name: 'Zoom', tier: 'Pro',
    category: 'Communication',
    logo: '/logos/zoom.svg',
    tile: 'linear-gradient(150deg,#2d8cff,#0b5cd5)',
    description: 'Meeting video tanpa batas waktu. 100 peserta, cloud recording 5GB, whiteboard, dan integrasi kalender Google/Outlook.',
    features: ['Meeting Tak Terbatas', '100 Peserta', 'Cloud Recording 5GB', 'Breakout Rooms', 'Whiteboard', 'Social Media Streaming'],
    plans: plans(12000, 32000, 60000, 112000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka zoom.us\n2. Login akun Pro\n3. Buat meeting\n4. Tanpa batas waktu',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['zoom-business', 'slack-pro'],
  },
  {
    slug: 'zoom-business',
    name: 'Zoom', tier: 'Business',
    category: 'Communication', logoText: 'Zoom Biz',
    tile: 'linear-gradient(150deg,#1d8cf8,#0a54b3)',
    description: 'Zoom untuk bisnis. 300 peserta, recording cloud 5GB, Zoom Phone add-on, managed domain, dan fitur enterprise.',
    features: ['300 Peserta', 'Company Branding', 'Managed Domain', 'Zoom Phone', 'Recording Transcripts', 'Admin Dashboard'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka zoom.us\n2. Login akun Business\n3. Setup branding\n4. Meeting enterprise',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['zoom-pro', 'slack-pro'],
  },
  {
    slug: 'discord-nitro',
    name: 'Discord', tier: 'Nitro',
    category: 'Communication', logoText: 'Discord',
    tile: 'linear-gradient(150deg,#5865f2,#2d3785)',
    description: 'Discord Nitro penuh — upload 500MB, streaming 4K 60fps, 2 boost server gratis, animated avatar, dan custom tag.',
    features: ['Upload 500MB', 'Streaming 4K 60fps', '2 Server Boost', 'Animated Avatar & Emoji', 'Custom Tag', 'Nitro Badge'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka Discord\n2. Login akun Nitro\n3. Semua fitur aktif\n4. Streaming 4K',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['telegram-premium', 'slack-pro'],
  },
  {
    slug: 'slack-pro',
    name: 'Slack', tier: 'Pro',
    category: 'Communication', logoText: 'Slack',
    tile: 'linear-gradient(150deg,#611f69,#2e0e33)',
    description: 'Platform komunikasi tim profesional. Riwayat pesan tak terbatas, 10GB storage per anggota, dan video huddle.',
    features: ['Riwayat Pesan Tak Terbatas', '10GB Storage/Anggota', 'Video Huddles', 'App Integrations', 'Workflow Builder', 'Screen Share'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka slack.com\n2. Login akun Pro\n3. Undang tim\n4. Mulai kolaborasi',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['zoom-pro', 'discord-nitro'],
  },
  {
    slug: 'telegram-premium',
    name: 'Telegram', tier: 'Premium',
    category: 'Communication', logoText: 'Telegram',
    tile: 'linear-gradient(150deg,#2aabee,#0e6fa0)',
    description: 'Telegram Premium — upload 4GB, download tercepat, konversi stiker, chat tanpa iklan, dan folder khusus.',
    features: ['Upload File 4GB', 'Download Prioritas', 'Tanpa Iklan', 'Reactions Eksklusif', 'Sticker Conversion', 'Voice-to-Text'],
    plans: plans(10000, 27000, 50000, 95000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Buka Telegram\n2. Login akun Premium\n3. Badge premium aktif\n4. Semua fitur unlocked',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['discord-nitro', 'zoom-pro'],
  },

  // ── Gaming ───────────────────────────────────────────────────────────────
  {
    slug: 'xbox-game-pass',
    name: 'Xbox Game Pass', tier: 'Ultimate',
    category: 'Gaming', logoText: 'Xbox',
    tile: 'linear-gradient(150deg,#107c10,#053805)',
    description: '300+ game premium Xbox, PC, dan EA Play — termasuk semua game first-party Microsoft di hari rilis. Cloud gaming included.',
    features: ['300+ Game Premium', 'Game di Hari Rilis', 'EA Play Included', 'Cloud Gaming', 'Xbox & PC', 'Perks & Rewards'],
    plans: plans(20000, 54000, 102000, 190000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Login Xbox Account\n2. Redeem kode Ultimate\n3. Cloud gaming aktif\n4. Main 300+ game',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['playstation-plus', 'ea-play-pro'],
  },
  {
    slug: 'playstation-plus',
    name: 'PlayStation Plus', tier: 'Deluxe',
    category: 'Gaming', logoText: 'PS Plus',
    tile: 'linear-gradient(150deg,#003087,#001544)',
    description: 'PS Plus Deluxe — akses ratusan game PS4/PS5, game klasik PS1/PS2/PSP, dan game trial eksklusif. Online multiplayer.',
    features: ['400+ Game Katalog', 'PS4 & PS5 Games', 'Game Klasik PS1/PS2', 'Online Multiplayer', 'Cloud Saves', 'Monthly Games'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['best_seller', 'instant'],
    activationGuide: '1. Login PSN\n2. Aktifkan Deluxe\n3. Download game gratis\n4. Online gaming',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['xbox-game-pass', 'ea-play-pro'],
  },
  {
    slug: 'nintendo-online',
    name: 'Nintendo Switch Online', tier: 'Expansion Pack',
    category: 'Gaming', logoText: 'Nintendo',
    tile: 'linear-gradient(150deg,#e4000f,#7a000a)',
    description: 'Online multiplayer Switch + game NES/SNES/N64/GB + DLC Expansion Pack Animal Crossing & Mario Kart 8.',
    features: ['Online Multiplayer', 'NES, SNES, N64, GB', 'Expansion Pack DLC', 'Cloud Saves', 'NSO App', 'Voucher Games'],
    plans: plans(15000, 40000, 75000, 140000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Login Nintendo Account\n2. Beli Expansion Pack\n3. Online gaming aktif\n4. Main N64 classics',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['xbox-game-pass', 'playstation-plus'],
  },
  {
    slug: 'ea-play-pro',
    name: 'EA Play', tier: 'Pro',
    category: 'Gaming', logoText: 'EA Play',
    tile: 'linear-gradient(150deg,#f26522,#7d2900)',
    description: 'Akses penuh semua game EA — FIFA, Battlefield, The Sims, Apex Legends Bundles, dan game baru di hari rilis.',
    features: ['Semua Game EA PC', 'Early Access 10 Jam', 'Game Baru Hari Rilis', 'EA Sport FC', 'Battlefield Series', 'Diskon 10%'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Login EA Account\n2. Aktifkan Pro\n3. Download game EA\n4. Early access aktif',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['xbox-game-pass', 'playstation-plus'],
  },
  {
    slug: 'ubisoft-plus',
    name: 'Ubisoft+', tier: 'Classic',
    category: 'Gaming', logoText: 'Ubisoft+',
    tile: 'linear-gradient(150deg,#1e3a8a,#0a1744)',
    description: 'Semua game Ubisoft — Assassin\'s Creed, Far Cry, Rainbow Six, Watch Dogs, The Crew. Plus DLC & ekspansi.',
    features: ['100+ Game Ubisoft', 'DLC & Ekspansi', 'Assassin\'s Creed Series', 'Far Cry Series', 'Cloud Saves', 'Early Access'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Login Ubisoft Connect\n2. Aktifkan Classic\n3. Download game\n4. Main semua seri',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['ea-play-pro', 'xbox-game-pass'],
  },
  {
    slug: 'steam-wallet',
    name: 'Steam Wallet', tier: 'Top Up',
    category: 'Gaming', logoText: 'Steam',
    tile: 'linear-gradient(150deg,#1b2838,#0a1020)',
    description: 'Isi saldo Steam untuk beli game, DLC, item in-game, dan hadiah. Proses instan, harga terbaik.',
    features: ['Instan ke Akun', 'Beli Game & DLC', 'CS2 Skins', 'Gift Card Steam', 'Workshop Items', 'Semua Region'],
    plans: [
      { name: 'Rp 50.000',  duration: 'Saldo',  price: 52000,  originalPrice: 55000, popular: true  },
      { name: 'Rp 100.000', duration: 'Saldo',  price: 104000, originalPrice: 110000 },
      { name: 'Rp 200.000', duration: 'Saldo',  price: 206000, originalPrice: 215000 },
      { name: 'Rp 500.000', duration: 'Saldo',  price: 512000, originalPrice: 530000 },
    ],
    warranty: 'Garansi Kirim', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Berikan Steam ID\n2. Saldo dikirim langsung\n3. Cek wallet Steam\n4. Belanja game',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['riot-gift-card', 'xbox-game-pass'],
  },
  {
    slug: 'riot-gift-card',
    name: 'Riot Games', tier: 'Gift Card',
    category: 'Gaming', logoText: 'Riot',
    tile: 'linear-gradient(150deg,#c89b3c,#5c400d)',
    description: 'Isi RP Valorant / LoL / Wild Rift dengan harga terbaik. Langsung masuk ke akun, proses instan.',
    features: ['Valorant Points', 'League of Legends', 'Wild Rift', 'Instan ke Akun', 'Semua Server', 'No Expire'],
    plans: [
      { name: '125 RP',   duration: 'Saldo',  price: 14000,  originalPrice: 16000, popular: false },
      { name: '650 RP',   duration: 'Saldo',  price: 48000,  originalPrice: 52000, popular: true  },
      { name: '1625 RP',  duration: 'Saldo',  price: 103000, originalPrice: 112000 },
      { name: '3325 RP',  duration: 'Saldo',  price: 200000, originalPrice: 220000 },
    ],
    warranty: 'Garansi Kirim', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Berikan Riot ID\n2. Pilih server\n3. RP masuk otomatis\n4. Beli skin favorit',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['steam-wallet', 'xbox-game-pass'],
  },

  // ── Business ─────────────────────────────────────────────────────────────
  {
    slug: 'shopify',
    name: 'Shopify', tier: 'Basic',
    category: 'Business', logoText: 'Shopify',
    tile: 'linear-gradient(150deg,#96bf48,#4a6324)',
    description: 'Platform e-commerce terbaik dunia. Buka toko online lengkap dengan payment, inventory, dan analytics bawaan.',
    features: ['Toko Online Lengkap', 'Payment Gateway', 'Inventory Management', 'App Store 8000+', 'Analytics & Reports', 'Multi Channel'],
    plans: plans(28000, 75000, 142000, 265000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 5 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka shopify.com\n2. Login akun Basic\n3. Setup toko\n4. Mulai jualan',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['wix-premium', 'squarespace'],
  },
  {
    slug: 'wix-premium',
    name: 'Wix', tier: 'Unlimited',
    category: 'Business', logoText: 'Wix',
    tile: 'linear-gradient(150deg,#FAAD00,#8b5d00)',
    description: 'Buat website profesional tanpa coding. Drag & drop editor, 900+ template, SEO tools, dan bandwidth tak terbatas.',
    features: ['Storage 35GB', 'Bandwidth Unlimited', 'Domain Gratis 1 Tahun', 'SEO Tools', 'Wix Analytics', 'Tanpa Iklan Wix'],
    plans: plans(18000, 48000, 90000, 170000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka wix.com\n2. Login akun Unlimited\n3. Buat website\n4. Publish online',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['squarespace', 'shopify'],
  },
  {
    slug: 'squarespace',
    name: 'Squarespace', tier: 'Business',
    category: 'Business', logoText: 'Squarespace',
    tile: 'linear-gradient(150deg,#1a1a1a,#000000)',
    description: 'Platform website dengan desain paling elegan. Template award-winning, e-commerce bawaan, dan SEO tools canggih.',
    features: ['Template Award-winning', 'E-commerce Unlimited', 'Custom Domain', 'SEO Tools Advanced', 'Email Campaigns', 'Analytics Pro'],
    plans: plans(22000, 60000, 112000, 210000, 0),
    warranty: 'Garansi 30 Hari', deliveryTime: '< 1 Menit',
    status: 'available', badges: ['instant'],
    activationGuide: '1. Buka squarespace.com\n2. Login akun Business\n3. Pilih template\n4. Publish website',
    termsConditions: commonTerms, faq: commonFaq, reviews: commonReviews,
    relatedSlugs: ['wix-premium', 'shopify'],
  },
]

// ─── Lookup helpers ──────────────────────────────────────────────────────────

export const catalogBySlug = Object.fromEntries(catalog.map(p => [p.slug, p]))

export function getProductBySlug(slug: string): CatalogProduct | null {
  return catalogBySlug[slug] ?? null
}

export const CATEGORIES: ProductCategory[] = [
  'AI Tools', 'Design', 'Streaming', 'Music', 'Learning',
  'Cloud', 'VPN & Security', 'Developer', 'Communication', 'Gaming', 'Business',
]

export function getProductsByCategory(cat: ProductCategory): CatalogProduct[] {
  return catalog.filter(p => p.category === cat)
}

export function getRelatedProducts(slug: string, limit = 4): CatalogProduct[] {
  const product = catalogBySlug[slug]
  if (!product) return []
  return product.relatedSlugs
    .map(s => catalogBySlug[s])
    .filter(Boolean)
    .slice(0, limit) as CatalogProduct[]
}

export function formatRupiah(value: number): string {
  return `Rp ${value.toLocaleString('id-ID')}`
}
