import {
  pgTable,
  text,
  integer,
  numeric,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";

export const ordersTable = pgTable("orders", {
  id: text("id").primaryKey(),
  customer_name: text("customer_name").notNull(),
  customer_email: text("customer_email").notNull(),
  customer_whatsapp: text("customer_whatsapp").notNull().default(""),
  product_slug: text("product_slug").notNull(),
  product_name: text("product_name").notNull(),
  plan_name: text("plan_name").notNull().default(""),
  plan_duration: text("plan_duration").notNull().default(""),
  quantity: integer("quantity").notNull().default(1),
  unit_price: numeric("unit_price", { precision: 15, scale: 2 }).notNull().default("0"),
  discount: numeric("discount", { precision: 15, scale: 2 }).notNull().default("0"),
  promo_code: text("promo_code"),
  payment_fee: numeric("payment_fee", { precision: 15, scale: 2 }).notNull().default("0"),
  total_payment: numeric("total_payment", { precision: 15, scale: 2 }).notNull(),
  payment_method: text("payment_method"),
  payment_method_label: text("payment_method_label"),
  payment_number: text("payment_number"),
  payment_expired_at: text("payment_expired_at"),
  pakasir_data: jsonb("pakasir_data"),
  status: text("status").notNull().default("pending"),
  notes: text("notes"),
  account_email: text("account_email"),
  account_password: text("account_password"),
  activation_guide: text("activation_guide"),
  warranty_days: integer("warranty_days").notNull().default(30),
  expiry_date: text("expiry_date"),
  created_at: timestamp("created_at").notNull().defaultNow(),
  updated_at: timestamp("updated_at").notNull().defaultNow(),
});
